// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn1-bOoS1Fivt5BZAHdFFkagBVgYVZyn4',
    appId: '1:180298288626:web:63d3c32441241718522f6b',
    messagingSenderId: '180298288626',
    projectId: 'iot-smart-system-a4490',
    authDomain: 'iot-smart-system-a4490.firebaseapp.com',
    storageBucket: 'iot-smart-system-a4490.firebasestorage.app',
    measurementId: 'G-3QMDM44NJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz10svRnzZJZKVpMrEzm7LiCQMuEcXIkA',
    appId: '1:180298288626:android:e2babab6656841a9522f6b',
    messagingSenderId: '180298288626',
    projectId: 'iot-smart-system-a4490',
    storageBucket: 'iot-smart-system-a4490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTNKK_AOSeDdgvrAPJ1WqkAjHDnq-3E3E',
    appId: '1:180298288626:ios:8c2e87f584fa474e522f6b',
    messagingSenderId: '180298288626',
    projectId: 'iot-smart-system-a4490',
    storageBucket: 'iot-smart-system-a4490.firebasestorage.app',
    iosBundleId: 'com.smart.iot.home.iotSmartHome',
  );
}
